# Generated by Django 3.1.9 on 2021-06-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narguile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narguile',
            name='image',
        ),
    ]
