# Generated by Django 3.1.9 on 2021-06-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narguile', '0002_remove_narguile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narguile',
            name='deleted_at',
        ),
    ]
